version: 2
jobs:
    build:
        working_directory: ~/repo
	machine: true
	branches:
	 only:
	   -master
	steps:
	  - checkout
	  - run: docker login repo.treescale.com -u $DOCKER_USER - p $DOCKER_PASS
	  - run:
	     name: build docker image
	     command: | 
	         echo: "deploying to development environment"
		 docker build -t mystery-box . 
		 docker tag mystery-box repo.treescale.com/aviquez96/mystery-box-dev:latest
		 docker push repo.treescale.com/aviquez96/mystery-box-dev:latest
